### ISSUE TITLE
[Docs] with examples on how to use it with erdpy

### ISSUE THREAD

**Issue by juliancwirko** [ElvenTools/elven-nft-minter-sc#11]
It would be good to have a docs section on elven.tools website with examples written for erdpy CLI usage for every endpoint and query. This will also be a perfect occasion to test all of them with erdpy properly.

Just a reminder: It is much simpler when you are using the [CLI](https://github.com/juliancwirko/elven-tools-cli)

**Comment by odrix** [comment]
hello,

I try to prepare a PR for this doc : one md file with erdpy's examples
I'll let you know when it's ready.

**Comment by juliancwirko** [comment]
Awesome, thanks!

**Comment by odrix** [comment]
I started this markdown in this project : https://github.com/odrix/elven-nft-minter-sc/blob/main/erdpy%20exemples.md

**Comment by juliancwirko** [comment]
Nice, I'll try to test them too.
