### ISSUE TITLE
[Docs] Drops and populateIndexes - docs and examples 

### ISSUE THREAD

**Issue by juliancwirko** [ElvenTools/elven-nft-minter-sc#14]
There are changes in the SC and CLI. We need to document them.

**Comment by tannerhallman** [comment]
I noticed in the docs that it's stated that anyone can call the `populate_indexes` method but I noticed that in the code, it's restricted to the owner only.

**Comment by juliancwirko** [comment]
Thanks for pointing it out. Could you show me where it is in the docs? Because it shouldn't be like that. The `populateIndexes` is a setup endpoint, and it is used only by the owner for the setup. The `shuffle` endpoint, which needs that, is for everyone.

**Comment by tannerhallman** [comment]
I'll keep my eyes open. I can't remember where I saw it.
