### ISSUE TITLE
Mint left NFTs

### ISSUE THREAD

**Issue by butavpaul** [ElvenTools/elven-nft-minter-sc#22]
If there are only 5 NFTs left to mint and you mint 6 NFTs at once the transaction will fail.
The mint should loop through each mint and check if's available for minting. Or this will trigger more gas fees?

**Comment by juliancwirko** [comment]
Yes, this isn't implemented yet. It is doable, but it will require more tests. For now, it is necessary to fit with the amount. So it is a responsibility of a frontend dapp to check that (using SC queries that are there).

But it is a good idea for improvement. Anyway, even if implemented, the frontend dapp should handle it properly not to confuse the user.

I will leave it as the new improvement idea. Thanks.

**Comment by butavpaul** [comment]
Yes, it's a good idea to check with the dapp the tokens left and inform the user. Thank you!

**Comment by juliancwirko** [comment]
Improvements are tracked on the project's Kanban board now.

https://github.com/orgs/ElvenTools/projects/7/views/1?pane=issue&itemId=47242279
