### ISSUE TITLE
Additional entries in the URIs/Asset section 

### ISSUE THREAD

**Issue by juliancwirko** [ElvenTools/elven-nft-minter-sc#3]
The only assets, for now, are the ipfs schema with the base CID and the image file name, and additionally, there is an ipfs gateway URI with the same CID and image name.

Some marketplaces require additional Assets/URIs entries like metadata JSON or collection JSON files. IMO this isn't a place for them. The metadata file for the image is encoded in the attributes, and it can include all additional URIs inside. 

But I could implement it as an option. Should it be implemented? Can someone explain why marketplaces require that?

**Comment by butavpaul** [comment]
https://youtu.be/nn0j52fP1yk?t=545
As Mihai from Trust.market is talking about here, the collection.json is needed for counting the rarities. I don't think it's mandatory but only makes the count easier. If you don't have one, I think the market will create one on their part.

**Comment by juliancwirko** [comment]
Hey, thanks for the input.

I see it is probably simpler for the particular marketplace, but I wonder why not read them from the main metadata JSON, which is perhaps parsed there anyway. In the Assets/Uris section, I would see only images, video, music, etc., not JSON files with configuration. It all should be included in the primary metadata, which has its CID encoded in the attributes. But this is just my opinion. I probably don't see the whole picture. 

The option to add more uris could be helpful anyway, so I will probably think about that after fixing all bugs.

**Comment by juliancwirko** [comment]
The simple adjustment, for now, will be to add the corresponding metadata to assets by default with the option not to do that. Then a more general solution would be needed.

**Comment by juliancwirko** [comment]
The possibility to attach the metadata URI is done on the development branch. For now, there won't be the possibility to add other URIs.

**Comment by juliancwirko** [comment]
You can now choose to attach the corresponding metadata file to the Assets/Uris. I'll leave this thread for the next steps, allowing you to add more entries there.
