### ISSUE TITLE
2 new things on explorer 

### ISSUE THREAD

**Issue by JezasBam** [ElvenTools/elven-nft-minter-sc#52]
I use `elven-tools nft-minter` , the problem is on explorer for collection now appear 2 more things `Rarities` and `Attributes` there u have a link : https://explorer.multiversx.com/nfts/STAFF-1b295e-13

And there is my explorer thing : https://devnet-explorer.multiversx.com/nfts/NATURE-bc41aa-02

u can do something about that , a little update for that creator , i use windows and i like more to work on windows than ubuntu and i don  t know at all to use mxpy or erdpy cuz i started learn what u created there :))

**Comment by JezasBam** [comment]
Ah , and please add the project : https://github.com/orgs/ElvenTools/projects/7 in this repo , i didn t see it ... only now .

**Comment by juliancwirko** [comment]
> I use `elven-tools nft-minter` , the problem is on explorer for collection now appear 2 more things `Rarities` and `Attributes` there u have a link : https://explorer.multiversx.com/nfts/STAFF-1b295e-13
> 
> And there is my explorer thing : https://devnet-explorer.multiversx.com/nfts/NATURE-bc41aa-02
> 
> u can do something about that , a little update for that creator , i use windows and i like more to work on windows than ubuntu and i don t know at all to use mxpy or erdpy cuz i started learn what u created there :))

The feature is implemented on the MultiversX API service side, I believe. For now, it is displayed only on the mainnet Explorer. So there is nothing to be done here. Elven Tools suggests using the [recommended file structure](https://docs.multiversx.com/tokens/nft-tokens#nftsft-fields) of the metadata json file, so it should be calculated automatically using your attributes. 

For example, you can see the rarities for this devnet NFT: https://devnet-api.multiversx.com/nfts/FCS-12ed15-0149 but they won't be displayed in the Explorer

In your case: https://devnet-api.multiversx.com/nfts/NATURE-bc41aa-02 looks like you don't have the metadata json file for this NFT. It isn't uploaded to IPFS so MultiversX API services can't load the required data/ The file doesn't exist here: https://ipfs.io/ipfs/bafybeientaoaekj235q765izus4ep7teaovlewg3ojfp6mdcevemvoz5ma/2.json

**Comment by JezasBam** [comment]
yeap , make sense , i will try to create a NFT collection with .json files (i don t know yet how , but i will check more ur creation too see if it s possible) and i will post it on devnet and mainet to see things , thanks for info , i will close the issue .

Thanks again .
