### ISSUE TITLE
How i can add these things ?

### ISSUE THREAD

**Issue by JezasBam** [ElvenTools/elven-nft-minter-sc#53]
Hi sorry to open the topic again, how do I add the stuff in the picture (Social, Atributes and Rarites)
And if you can't use what you have created for the moment, do you think you can make an update please?

Soon I want to get a collection of NFTs, and I would like to add these because I don't know how to use mxpy or erdpy, no matter how hard I try to install them there are a lot of problems .....

![image](https://github.com/ElvenTools/elven-nft-minter-sc/assets/99503710/36913f9a-8d0d-498b-95ea-b12f7a72def4)
Link :
https://explorer.multiversx.com/nfts/COW-cd463d-16af

**Comment by JezasBam** [comment]
Oh and if it's possible to close the rest of the Issues because they are from 2022 and I don't think they belong here anymore ...

**Comment by JezasBam** [comment]
Some projects have these things available and some don't that's why I'm very confused if I need to get explorer links for them , in .json everything seems to be ok , I'm super confused ...

**Comment by juliancwirko** [comment]
Hi, some things are not saved on the chain and depend only on MultiversX services, like Explorer. To do proper branding, you would need to submit a branding request by opening a Pull Request on: https://github.com/multiversx/mx-assets
You can also try: https://assets.multiversx.com/

The docs about it; https://docs.multiversx.com/tokens/nft-tokens/#branding

**Comment by JezasBam** [comment]
WoW , i never know https://assets.multiversx.com/ exist , in github i didn t see it , thanks a lot and sorry again for disturbing ! <3 !

I will close this one myslef ,i don t like to let open things ! <3
